import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import prisma from "./lib/prisma";
import Link from "next/link";
import Sidebar from "../components/sidebar";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="min-h-screen max-w-full flex antialiased">
          <div className="w-full">{children}</div>
        </body>
      </html>
    </SessionWrapper>
  );
}
